export const SET_UNIT_LIST = "SET_UNIT_LIST";
export const UNITS_LIST = "UNITS_LIST";
export const SET_UNIT_DETAIL = "SET_UNIT_DETAIL";
export const UNIT_DETAIL = "UNIT_DETAIL";
export const SET_FILTERED_UNIT_LIST = "SET_FILTERED_UNIT_LIST";
export const FILTERED_UNIT_LIST = "FILTERED_UNIT_LIST";